---
  - name: copy hosts 
    action: copy src=/etc/hosts dest=/etc/hosts

  - name: ntp is running
    action: service name=ntp state=started
  - name: configure ntp
    action: template src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
    - restart ntp

  - name: /mnt/nfs is in fstab
    action: "mount name=/mnt/nfs src=googoocluster:/export/clusterfs fstype=nfs state=present"
  - name: /mnt/nfs is mounted
    action: "mount name=/mnt/nfs src=googoocluster:/export/clusterfs fstype=nfs state=mounted"

