---
  - name: destination location exists
    action: file path=/home/pi/googoocluster state=directory owner=pi group=pi mode=0755   
  - name: download this repo
    action: "git repo=https://github.com/trubalcain/googoocluster dest=/home/pi/googoocluster"
  - name: git pull
    action: "shell cd /home/pi/googoocluster && git pull"
  - name: repo owned by pi 
    action: file path=/home/pi/googoocluster state=directory owner=pi group=pi recurse=yes 

