---
  - name: install munge 
    apt: pkg=munge state=installed

  - name: install munge key
    action: copy src=munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0600
    notify:
    - restart munge

  - name: munge is started
    action: service name=munge state=started

  - name: install slurm packages
    apt: name={{item}} state=installed
    with_items:
      - slurm-wlm
      - slurmd
      - slurm-wlm-doc
      - slurm-wlm-basic-plugins
      - slurm-wlm-torque


  - name: touch slurm log file and change ownership
    file: path=/var/log/slurm_jobacct.log owner=slurm state=touch

  - name: create slurm state dir and change ownership
    file: path=/var/slurm owner=slurm state=directory mode=0755

  - name: slurm is configured
    action: template src=slurm.conf.j2 dest=/etc/slurm-llnl/slurm.conf owner=slurm
    notify:
    - restart slurmd

  - name: slurmd is started
    action: service name=slurmd state=started
