---
  - name: install headnode packages from apt
    apt: name={{item}} state=installed
    with_items:
      - git
      - screen
      - environment-modules
      - gfortran
      - dnsmasq
      - dnsutils
      - nfs-kernel-server
      - nfs-common
	  - apache2

  - name: install ansible
    action: pip name=ansible state=latest 

  - name: configure nfs
    action: template src=exports.j2 dest=/etc/exports   
  - name: rpcbind is running
    action: service name=rpcbind state=started enabled=yes
  - name: nfs is running
    action: service name=nfs-kernel-server state=started enabled=yes
  - name: exportfs
    action: command exportfs -a

  - name: copy iptables config
    action: copy src=firewall.conf dest=/etc/firewall.conf
  - name: copy iptables if-up script
    action: copy src=iptables dest=/etc/network/if-up.d/iptables
  - name: restore iptables config
    action: shell iptables-restore -! < /etc/firewall.conf
  - name: configure on forwarding
    action: lineinfile dest=/etc/sysctl.conf regexp=^net.ipv4.ip_forward line=net.ipv4.ip_forward=1
  - name: turn on forwarding
    action: shell echo 1 > /proc/sys/net/ipv4/ip_forward
