---
  - name: point dns at engineering dns server
    action: template src=resolv.conf.j2 dest=/etc/resolv.conf
  - name: Update APT cache
    apt: update_cache=yes cache_valid_time=3600
  - name: install common packages
    apt:  name={{item}} state=installed
    with_items:
      - python-apt
      - python-dev
      - python-setuptools
      - openmpi-bin
      - openmpi-doc
      - libopenmpi-dev
      - hpcc
      - liblapack-dev
      - vim
      - pdsh

  - name: install pip
    action: easy_install name=pip