---
  - name: point dns at engineering dns server
    action: template src=resolv.conf.j2 dest=/etc/resolv.conf

  - name: update apt-cache
  - apt: update_cache=yes
	
  - name: install python-apt
  - apt: python-apt

  - name: install pip
    action: easy_install name=pip

  - name: install common packages
  - apt: name={{item}} state=installed
    with_items:
    - python-dev
    - python-setuptools
    - openmpi-bin
    - openmpi-doc
    - libopenmpi-dev
    - hpcc
    - liblapack-dev
    - vim-gtk
    - pdsh

