---
  - name: point dns at google
    action: template src=resolv.conf.j2 dest=/etc/resolv.conf

  - name: update apt-cache
    action: command apt-get -y update
  - name: install python-apt
    action: command apt-get -y install python-apt

  - name: install apt packages
    action: apt pkg={{item}} state=installed
    with_items:
    - python-dev
    - python-setuptools


  - name: install pip
    action: easy_install name=pip

  - name: install pip packages
    action: pip name={{item}} state=present
    with_items:
    - pyzmq
    - pyasn1
    - PyCrypto
    - python-keyczar


  - name: start fireball
    action: fireball

